-
  name: 'Standard'
  uriPattern:    'standard(/{@action})'
  defaults:
    '@package':    'We.Upload'
    '@controller': 'Standard'
    '@action':     'index'
    '@format':     'html'
-
  name: 'Standard'
  uriPattern:    '(standard)'
  defaults:
    '@package':    'We.Upload'
    '@controller': 'Standard'
    '@action':     'index'
    '@format':     'html'